twig:
    default_path: '%kernel.project_dir%/templates'
#    Activation du theme bootstrap 5 pour les formulaires du site
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:

        site_name: 'Le Blog de Batman'
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'


when@test:
    twig:
        strict_variables: true
